### ISSUE TITLE
Update to new Function interface

### ISSUE THREAD

**Issue by bamos** [locuslab/mpc.pytorch#19]
Is somewhat involved since `LqrStep` uses a lot of class attributes for the forward and backward pass

**Comment by GPrathap** [comment]
Any update on this?

**Comment by tlangerak** [comment]
I would also like to know what the status is on this issue.

**Comment by GPrathap** [comment]
I have done the fix on my repo, I haven't verified fully, but you may check https://github.com/GPrathap/mpc.pytorch.git

**Comment by bamos** [comment]
Updated in https://github.com/locuslab/mpc.pytorch/commit/bf19cd4405d8242e93f4c0a5464739f98798a833
