### ISSUE TITLE
GradMethods.Analytic Example

### ISSUE THREAD

**Issue by juanmed** [locuslab/mpc.pytorch#23]
Hello,

I was wondering if you had any examples in which the `GradMethods.ANALYTIC` option is used. I would like to see how to implement the calculation of the jacobian for your library to use it. Looking at the code I see one needs to implement the `grad_input` method, but would like to know more details. Right now I am having an issue in which when I try to use `GradMethods.ANALYTIC` the size of the matrices do not match in the `forward` method of my dynamics scripts (inside env_dx folder).

Your feedback will be very appreciated.

- Juan

**Comment by bamos** [comment]
Hi -- at some point these were working: https://github.com/locuslab/mpc.pytorch/blob/dc6ae9f6e3858510a5df96592fac3a3a17590b2a/mpc/dynamics.py

And the tests using them were passing: https://github.com/locuslab/mpc.pytorch/blob/dc6ae9f6e3858510a5df96592fac3a3a17590b2a/tests/test_mpc.py

Although something may have changed, let me know if we should fix anything in the main code.

-b.
