### ISSUE TITLE
RuntimeError: Legacy autograd function with non-static forward method is deprecated.

### ISSUE THREAD

**Issue by Meruem10** [locuslab/mpc.pytorch#33]
Dear all,

Running the example notebooks (Time-Varying Linear Control or Pendulum), I get the following error:

RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

Does anybody know how to resolve this issue?

Thank you in advance!

**Comment by Meruem10** [comment]
I just saw, that an issue has already been opened for the same issue here: https://github.com/locuslab/mpc.pytorch/issues/28

Sorry for the duplicate!

**Comment by bamos** [comment]
Updated in https://github.com/locuslab/mpc.pytorch/commit/bf19cd4405d8242e93f4c0a5464739f98798a833
