### ISSUE TITLE
No State Constraints in Mpc Solver

### ISSUE THREAD

**Issue by sichaozhang1112** [locuslab/mpc.pytorch#41]
hello mpc.pytorch developer,
first of all, mpc.pytorch is an amazing and fast mpc solver.  however, i found there is no constraints for states for input of this mpc solver. although solving was fast, the solution did not satisfy state constraint conditions.
did i miss this feature or it is just not developed yet?
PS: the mpc expression in code does not include state constraints either
```
 min_{tau={x,u}} sum_t 0.5 tau_t^T C_t tau_t + c_t^T tau_t
                        s.t. x_{t+1} = f(x_t, u_t)
                            x_0 = x_init
                            u_lower <= u <= u_upper
```
sincerely asking,
sichao

**Comment by sichaozhang1112** [comment]
> That's correct, we don't have general state constraints implemented

thx for reply. i think i can try, if it will work, expressing x_k+1 in the form of a*x_init+sum{b_i*u_i}, therefore using control constraints to represent constraint of states.

**Comment by abdelhakim96** [comment]
Hi, @sichaozhang1112 
Im interested in this feature as well! 
any progress in this regard?

**Comment by sichaozhang1112** [comment]
> 

sorry, i did not continue this assumption but turned to build own optimization network. so, its feasibility still needs to be verified.

**Comment by xdChen-me** [comment]
hello，do you have any progress？

> Hi, @sichaozhang1112 Im interested in this feature as well! any progress in this regard?

**Comment by sichaozhang1112** [comment]
> hello，do you have any progress？
> 
> > Hi, @sichaozhang1112 Im interested in this feature as well! any progress in this regard?

nope, i turned to build own learning-based mpc solver.
