### ISSUE TITLE
Numpy Version Spec Causes Conda Issues for Env Export

### ISSUE THREAD

**Issue by shieronymus-slingshot** [locuslab/mpc.pytorch#42]
Hello,

I'm running into an error using the "mpc" package, installed via Pip, but in a Conda environment.

When trying to export the environment ("conda env export > env.yaml"), I get this error:
```
InvalidVersionSpec: Invalid version '1<2': invalid character(s)
```

The manual fix is to edit the <ENV_BASE_DIR>/lib/python3.8/site-packages/mpc-0.0.4.dist-info/METADATA file, changing:
```
Requires-Dist: numpy (>=1<2)
``` 
to
```
Requires-Dist: numpy (>=1,<2)
```

It looks like this might be fixed in the code by changing line 14 of setup.py from ```'numpy>=1<2', 'torch'``` to ```        'numpy>=1,<2', 'torch'```.

Would you be willing to make this change and publish a new version?

Thank you,
Seth

**Comment by bamos** [comment]
I just updated that line in https://github.com/locuslab/mpc.pytorch/commit/63732fa85ab2a151045493c4e67653210ca3d7ff,  can you try re-installing it from git:

```
pip install git+git://github.com/locuslab/mpc.pytorch.git
```
