### ISSUE TITLE
[BUG] DEPRECATION: mpc 0.0.4 has a non-standard dependency specifier numpy>=1<2

### ISSUE THREAD

**Issue by giuseppefilippone** [locuslab/mpc.pytorch#43]
Hi!

I was updating numpy in Python 3.8 and I got the following warning:

> DEPRECATION: mpc 0.0.4 has a non-standard dependency specifier numpy>=1<2. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of mpc or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

Can I solve the problem somehow? Thank you in advance!

**Comment by sakoht** [comment]
This is a big issue: anyone doing `pip install mpc` with an up-to-date `pip` gets an error.

It looks like the repo is updated, but pypi has something older as the 0.0.4 version, which does not have a tag in the repo.  

This probably requires:
- a 0.0.4 tag on whatever commit was used to make that version in PyPi
- a 0.0.5 tag on the current vresion
- a copy of 0.0.5 put on pypi

I'm currently working around this by doing:
```
pip install -e git+https://github.com/locuslab/mpc.pytorch@63732fa85ab2a151045493c4e67653210ca3d7ff#egg=mpc
```

To get the current `master` branch from 2yrs ago.

**Comment by bamos** [comment]
Hi, sorry about that. I've just updated the pypi version [here](https://pypi.org/manage/project/mpc/releases/) to the most recent commit here

**Comment by sakoht** [comment]
Thanks @bamos!!
