### ISSUE TITLE
Could not import mpc, QuadCost, mpc from mpc

### ISSUE THREAD

**Issue by rahulbhalley** [locuslab/mpc.pytorch#9]
Following **Example: Time-Varying Linear Control** on [project page](https://locuslab.github.io/mpc.pytorch/) I failed importing `mpc`, `QuadCost`, `LinDx` from `mpc` package. 
I installed `mpc` with `pip install mpc` and the version is `0.0.2`.

**Comment by bamos** [comment]
Thanks! That import statement is incorrect. I just fixed the example, and have also added a Jupyter notebook for it that should work: https://github.com/locuslab/mpc.pytorch/blob/master/examples/Time%20Varying%20Linear-Quadratic%20Control.ipynb

I'm going to add significantly more docs/examples over the next few weeks. If you're interested you can follow them at https://github.com/locuslab/mpc.pytorch/issues/8
